### PR TITLE
V2.0 glossary test

### PR DESCRIPTION
**Pull request by DrewThomasson**
@ROBERT-MCDOWELL 

Was looking at adding a Glossary to the README 🤔 

Only Downside is for it to function we have to remove the emojis from the chapter titles :(

Thoughts?

Or any suggestions on where to put it if you approve of it? 🤔

### CODE REVIEW

**Comment by ROBERT-MCDOWELL** [comment]
README can survive without emojis I think :)

**Comment by DrewThomasson** [comment]
tru tru 👍 

So your fine with that placement of it?

**Comment by ROBERT-MCDOWELL** [comment]
LGTM, language code must be 3 letters btw ;)

**Comment by DrewThomasson** [comment]
Oo good catch

**Pull request closed without merging**
