### PR TITLE
fixed the ebook2audiobook fix the file itself by removing the unwante…

### PR DESCRIPTION
**Pull request by DrewThomasson**
fixed the ebook2audiobook fix the file itself by removing the unwanted Windows-style line endings (\r), ensuring the script is compatible with Unix-based systems like macOS. using dos2unix

### CODE REVIEW

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL ?

I had to run `dos2unix` on `ebook2audiobook.sh` to fix the unwanted Windows-style line endings (\r)

**Comment by DrewThomasson** [comment]
just fixed typo in readme also

**Comment by DrewThomasson** [comment]
just removed redundancy and the zip link thing in the readme cause were not using that anymore lol

**Comment by DrewThomasson** [comment]
updated the --help command output example in the readme :)

**Comment by DrewThomasson** [comment]
updated the docker instructions in the readme :)

**Comment by DrewThomasson** [comment]
Updated the Mac launcher to something that will work :)

**Comment by ROBERT-MCDOWELL** [comment]
> @ROBERT-MCDOWELL ?
> 
> I had to run `dos2unix` on `ebook2audiobook.sh` to fix the unwanted Windows-style line endings (\r)

I fixed it in a waiting PR

**Comment by DrewThomasson** [comment]
Oh lol

**Comment by DrewThomasson** [comment]
This one? 

https://github.com/DrewThomasson/ebook2audiobook/pull/104

**Comment by ROBERT-MCDOWELL** [comment]
Y

**Pull request closed without merging**
