### PR TITLE
Made a fix for loading and downloading the fine-tuned tts models

### PR DESCRIPTION
**Pull request by DrewThomasson**
We don't have to use this but it'll at least help you get a better idea on what to do to fix the issue that we were having.

### CODE REVIEW

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL 

:)?

**Comment by DrewThomasson** [comment]
Cause I realize the only issue we are having at this point seems to be that it isn't downloading the fine-tuned model

**Comment by ROBERT-MCDOWELL** [comment]
we don't need to download it manually, the fact to call TTS(/hf/path) should do it. it worked before so there is no reason it does not work anymore unless a little glitch is the code that perturbs the cache creation.
downloading manually creates things more complex like check everytime if the folder exists etc... and ask more maintenance for long term code.

**Comment by DrewThomasson** [comment]
Mmm fair fair still learned some lol

**Comment by ROBERT-MCDOWELL** [comment]
I'm working on it. in same time a server update is causing a segfault of a lot of compiled app I'm running. I must check if it's a major issue from glibc or my old apps which are not compilable anymore... a nightmare...

**Pull request closed without merging**
