### PR TITLE
added updated morgan freeman model to list

### PR DESCRIPTION
**Pull request by DrewThomasson**
added my updated re-trained morgan freeman model to the list of fine-tuned xtts models with the link to its respective ref.wav file to use in inference of this model.

### CODE REVIEW

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL 

Do you approve this merge?

**Comment by ROBERT-MCDOWELL** [comment]
how do you want to use them in production mode? don't forget that now we support more than 1100 languages and we should be aware of how to list and order them....

**Comment by DrewThomasson** [comment]
hm.... not sure

i know these are just the xtts fine-tuned models but i suppose the ref.wav files with them could be used for other voice cloning models too...

**Comment by DrewThomasson** [comment]
but these are english models and english voices.....

**Comment by DrewThomasson** [comment]
hm.... we should probs call on discord about his or something so we can communicate what eachothers plans and goals are

**Comment by DrewThomasson** [comment]
I'll look at drawing up some interface design ideas and just give me any times your open to call so we can shoot ideas back and forth at eachother

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL 

what do you think of that layout?

I changed the David attenburo model details to what i think you meant

**Pull request closed without merging**
