### PR TITLE
Last PR  before merge to main

### PR DESCRIPTION
**Pull request by ROBERT-MCDOWELL**
this last PR makes me think it should be ok for the merge of your main branch.
we reached 1k stars, so it's time to bring them to the new version...
it will also bring certainly more contributors..

### CODE REVIEW

**Review by DrewThomasson — APPROVED** [review]

**Comment by DrewThomasson** [comment]
Yes yes agreed :D

I'll run a test, in Vietnamese and in English to make sure that it can successfully use the fairseq and XTTS model

And then double check the readme

And then merge 👌

**Comment by ROBERT-MCDOWELL** [comment]
I will push a new PR today, there are still things to change. about fairseq model we must still integrate it. Also I just learned that the torchaudio we are using is not optimized for very long audio, so I will modify the requirements and pyproject.toml

**Comment by ROBERT-MCDOWELL** [comment]
I have to recheck the language_mapping again, wrong ISO codes.

**Comment by ROBERT-MCDOWELL** [comment]
the facebook/mm-tts is about 1TB :-| . so not good to import it all locally ...

**Comment by DrewThomasson** [comment]
lol yeah well just have them download the fairseq models on the fly,

It's only around 135 mb for each anyway

**Comment by DrewThomasson** [comment]
> I have to recheck the language_mapping again, wrong ISO codes.

Oh yeah, 

I think the iso code values are fine in the `language_mapping` it's just only sending the xtts format language codes for every language, and needs to be sending the iso style codes for specifically the fairseq model inference

You probs already 10 steps ahead of me on this though XD

**Comment by DrewThomasson** [comment]
oh yeah and probably good to have the faiseq models generate:

- With voice cloning inference if voice is given

- Without voice cloning inference if no voice is given (For faster inference if its using VITS for the voice cloning)
-

**Comment by DrewThomasson** [comment]
I'll run some fairseq speed testing on my end with and without voice cloning to double check

**Comment by ROBERT-MCDOWELL** [comment]
> oh yeah and probably good to have the faiseq models generate:
> 
> * With voice cloning inference if voice is given
> * Without voice cloning inference if no voice is given (For faster inference if its using VITS for the voice cloning)

we can do it with

 tts --out_path output/path/speech.wav --model_name "//<model_name>" --source_wav <path/to/speaker/wav> --target_wav <path/to/reference/wav>

**Comment by DrewThomasson** [comment]
I'll see about finding a more automated way of generating a bunch more of the test ebook files

**Comment by DrewThomasson** [comment]
https://github.com/DrewThomasson/ebook2audiobook/pull/58

?🙏

**Comment by DrewThomasson** [comment]
Might have some free time to try a go at implementing the fairseq model for the finaly 2.0 update in a bit, Unless your already working on it lol. 
I just don't wanna get in the way with conflicting pushes if your already working on it 😅

**Comment by ROBERT-MCDOWELL** [comment]
I'm already working on it since 2 days now. prepare the repo for the 1142 languages...

**Comment by DrewThomasson** [comment]
## kk 👍 
vits2? 👀 👀 👀 

## oh also
- In the meantime should I fix the other read me languages to get them aligned with the `ebook2audiobook.sh` stuff or are you already set with that?

**Comment by ROBERT-MCDOWELL** [comment]
yes, the readme should be rebased. like adding the new options (--ebook-dir for ex) and behavior (no need to add True to the option, like --headless etc..), the video screenshot too :)

**Comment by DrewThomasson** [comment]
👍👍 I'll get on that 🫡

**Pull request merged**
