### PR TITLE
added Fairseq supported language list to english readme

### PR DESCRIPTION
**Pull request by DrewThomasson**

### CODE REVIEW

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL 👍 ?

**Comment by DrewThomasson** [comment]
I was looking at putting the help command modification but only after your push lol 🤷

**Comment by ROBERT-MCDOWELL** [comment]
it's ok you can push as long as it's only the readme..
I'm almost good, testing with real ebooks with various language and length, fix the metadatas parsinng,  tough tough work.... :-\

**Comment by DrewThomasson** [comment]
Your messing with the metadata parsing code?😅😅😅

XD

My code I wrote for that was barley hanging on by a thread XD😅😅😅

🫡🫡🫡

**Comment by ROBERT-MCDOWELL** [comment]
metadata was nothing to fix, the most hard is to filter all text that are in a book like technical editor stuff etc....

**Comment by DrewThomasson** [comment]
Ohhhhhh 👀✨

Fancy 👀✨

**Comment by DrewThomasson** [comment]
## Just realized that the xtts version we are using using supports hindi also!

## ✨ 

Languages
XTTS-v2 supports 17 languages: English (en), Spanish (es), French (fr), German (de), Italian (it), Portuguese (pt), Polish (pl), Turkish (tr), Russian (ru), Dutch (nl), Czech (cs), Arabic (ar), Chinese (zh-cn), Japanese (ja), Hungarian (hu), Korean (ko) **Hindi (hi).**

## [Source](https://huggingface.co/coqui/XTTS-v2)

**Pull request merged**
