### PR TITLE
added new options in conf.py, custom_model still in dev

### PR DESCRIPTION
**Pull request by ROBERT-MCDOWELL**

### CODE REVIEW

**Review by DrewThomasson — APPROVED** [review]

**Comment by DrewThomasson** [comment]
Nice nice 👍 

Did you manage to figure out why it's been downloading the standard Xtts model files in all the fine-tuned model folders?

**Comment by DrewThomasson** [comment]
Cause I was scratching my head going mad that the viet model was saying things like it was using the wrong model


Then I compared the HASHes of two fine-tuned models that were suppose to be diffrent and found they were identical

**Comment by DrewThomasson** [comment]
Oh yeah you did say the custom_model was in dev

**Comment by ROBERT-MCDOWELL** [comment]
> Did you manage to figure out why it's been downloading the standard Xtts model files in all the fine-tuned model folders?
??? are you sure of that?

**Comment by ROBERT-MCDOWELL** [comment]
ha ok you talk about custom_model... not finished. hassle about zip check and else... will push today later...

**Comment by DrewThomasson** [comment]
Talk later GN same zzz

**Comment by DrewThomasson** [comment]
heck, after a re-install trying to convert anything leads to this 

```bash
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/Users/drew/Desktop/ebook2audiobook/lib/functions.py", line 147, in prepare_dirs
    os.makedirs(session['custom_model_dir'], exist_ok=True)
  File "<frozen os>", line 210, in makedirs
  File "<frozen posixpath>", line 103, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
Caught DependencyError: expected str, bytes or os.PathLike object, not NoneType
convert_ebook() Exception: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by DrewThomasson** [comment]
But u probs already know that lol

**Comment by ROBERT-MCDOWELL** [comment]
refresh your page...

**Comment by DrewThomasson** [comment]
I'll check again later today

**Comment by DrewThomasson** [comment]
yup still has the issue

here is the error

```bash
UniDic dictionary not found or incomplete. Downloading now...
download url: https://cotonoha-dic.s3-ap-northeast-1.amazonaws.com/unidic-3.1.0.zip
Dictionary version: 3.1.0+2021-08-31
Downloading UniDic v3.1.0+2021-08-31...
unidic-3.1.0.zip: 100%|████████████████████████████████| 526M/526M [01:47<00:00, 4.88MB/s]
Finished download.
Downloaded UniDic v3.1.0+2021-08-31 to /Users/drew/ebook2audiobook/python_env/lib/python3.12/site-packages/unidic/dicdir
Dictionary ok
* Running on local URL:  http://0.0.0.0:7860

To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "/Users/drew/ebook2audiobook/lib/functions.py", line 147, in prepare_dirs
    os.makedirs(session['custom_model_dir'], exist_ok=True)
  File "<frozen os>", line 210, in makedirs
  File "<frozen posixpath>", line 103, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
Caught DependencyError: expected str, bytes or os.PathLike object, not NoneType
convert_ebook() Exception: expected str, bytes or os.PathLike object, not NoneType

```

**Comment by DrewThomasson** [comment]
### Was a fresh install was testing on English with this file

[test.txt](https://github.com/user-attachments/files/18219301/test.txt)

### And this is the full log of the install and test run

[eng_test_log.txt](https://github.com/user-attachments/files/18219302/eng_test_log.txt)

**Comment by DrewThomasson** [comment]
:/ heck

**Pull request merged**
