### PR TITLE
renamed split_long_sentence to get_sentences, added punctuation for each language into language_mapping, unused code removed

### PR DESCRIPTION
**Pull request by ROBERT-MCDOWELL**
Please test it with a long chapter and long sentences in 3 different language signs (english,arabic,chinese for ex)
as I cannot do anything with my 16 years old laptop core duo with a 512MB nvidia GPU :-|

### CODE REVIEW

**Comment by ROBERT-MCDOWELL** [comment]
I'm working to add all languages in language_mapping... tedious work...

**Comment by DrewThomasson** [comment]
:o

Anything I could do to help( Whenever I have some time to spare every now and then?)
- Sadly I might not have much time to put into this finals are coming up lol :(

**Comment by ROBERT-MCDOWELL** [comment]
It's ok I almost finished. 20 by 20 after a chagpt limitations with the right request without hallucinations...
maybe the best would be to test various new languages? does it need to update the code?

**Comment by ROBERT-MCDOWELL** [comment]
for the voices I have already some.. we will share the job but not a priority for now.. the v2 merge is...

**Comment by DrewThomasson** [comment]
Your code works in a space too btw! :D

https://huggingface.co/spaces/drewThomasson/ebook2audiobook_v2.0

**Comment by ROBERT-MCDOWELL** [comment]
Hurrayy! :D... the get_sentences + enable_text_splitting=True is not to bad, but sometimes word repetition and not enough space between some end of sentence and start of the following....

**Comment by DrewThomasson** [comment]
hm, Well I think the word repetition was already a thing.

**Comment by ROBERT-MCDOWELL** [comment]
this will be the last thing to solve before the merge...  GN!

**Comment by DrewThomasson** [comment]
kk GN!

**Pull request merged**
