### PR TITLE
Fixed f-string syntax errors :)

### PR DESCRIPTION
**Pull request by DrewThomasson**
@ROBERT-MCDOWELL 

?

:)

### CODE REVIEW

**Comment by DrewThomasson** [comment]
Thats needed to allow it run run in the hugginface space and the docker is why lol

**Comment by DrewThomasson** [comment]
Just making sure that your also approving every merge I do so we don't run into any errors on your end lol 

:)

**Comment by ROBERT-MCDOWELL** [comment]
yeah I can do it only after you merged my PR, if not we will have the same shite that last time ;-|

**Comment by DrewThomasson** [comment]
Kk well I'll let u fix it then lol

Don't want conflicts in merges lol

**Pull request closed without merging**
