### PR TITLE
Update functions.py fixes all txt files being default set to english

### PR DESCRIPTION
**Pull request by DrewThomasson**
fixes all txt files being default set to english

(txt files have no language metadata is why)

so I made it just ignore the language check for txt files

### CODE REVIEW

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL

?

**Comment by ROBERT-MCDOWELL** [comment]
ah yes, forgot metadata changes on each file... thanks!

**Comment by ROBERT-MCDOWELL** [comment]
but I'm still rebasing  functions.py... you can maybe modify the generate_ebook to add the right meta and regenerate all?

**Comment by DrewThomasson** [comment]
Yeah I'll work on trying to modify all those objects and such in tokenizer.py 

That is externally in our code adding to it 

👍

**Comment by DrewThomasson** [comment]
I'm also running into issues of improper quoting in f strings and such

But that's probs what your working on right now

I applied a fix and I'll show you the branch to show the changes if it helps for u in your re-basing

👍🫡

**Comment by ROBERT-MCDOWELL** [comment]
ok

**Comment by DrewThomasson** [comment]
Here,

You can ignore the other stuff i did the main file 

i dont plan on merging it 

https://github.com/DrewThomasson/ebook2audiobook/pull/69

**Comment by ROBERT-MCDOWELL** [comment]
ok, I'm finalizing the chapters extraction to audio. I found a way to avoid all unwanted pages....

**Comment by DrewThomasson** [comment]
🔥👀👀👀👀

**Comment by ROBERT-MCDOWELL** [comment]
about custom model (url and upload): now it's saved to the current user tmp folder used once and the deleted when conversion is done to avoid upload brute force or hard drive space shrinking. I rebased totally the logic, there was some bugs and code going nowhere...

**Comment by DrewThomasson** [comment]
Nice nice nice

**Comment by ROBERT-MCDOWELL** [comment]
in fact we should keep it once uploaded and does not allow the user to upload more unless if the custom is deleted from gradio. in headless mode it surely needs a new option to delete it... anyhow I'm not on this topic for now... my laptop crashed and had to reinstall python_env

**Pull request closed without merging**
