### PR TITLE
V2.0 update readme improved and added assets folder

### PR DESCRIPTION
**Pull request by DrewThomasson**
- Updated more things in the readme

- Added assists folder for everything in the readme for better organization

- moved v1.0 code into the legacy folder

### CODE REVIEW

**Comment by DrewThomasson** [comment]
@ROBERT-MCDOWELL 

👍 ?

**Comment by DrewThomasson** [comment]
The other language ReadMe files will of course need to be completely re-written lol

we have changed quite a lot

**Comment by ROBERT-MCDOWELL** [comment]
FINE

**Comment by DrewThomasson** [comment]
Don't worry I'll be re-writing them lol

**Pull request merged**
